### ISSUE TITLE
check_process count != returns always crit

### ISSUE THREAD

**Issue by Tux12Fun** [mickem/nscp#159] opened 2015-06-11 09:23 UTC
Hi,

I tested with two Calculators in Windows. But the Result is always CRIT.

Two should be OK State. Everything else should be CRIT.

sm01:/usr/local/icinga2/nagiosplugins # ./check_nrpe -H 10.1.6.6 -c "check_process" -a 'process=calc.exe' 'filter=started' 'show-all' 'debug' 'crit=count != 2'
CRITICAL: critical(calc.exe=started), calc.exe=started

sm01:/usr/local/icinga2/nagiosplugins # ./check_nrpe -H 10.1.6.6 -c "check_process" -a 'process=calc.exe' 'filter=started' 'show-all' 'debug' #'crit=count != 2'
OK: calc.exe=started, calc.exe=started|'calc.exe state'=1;0;0 'calc.exe state'=1;0;0 'count'=2;0;0

**Comment by mickem** [comment] 2015-08-29 15:01
count is broken in 0.4.3 and will not work as expected (this will  be fixed in 0.4.4).
The problem is that the expression is evaluated on each line maning it eill match 1, 2, 3, 4, 5... max not jsut max as expected.

**Closed** 2015-09-26 20:46 UTC
Labels: bug
