### ISSUE TITLE
Agent not fully terminating on service restart

### ISSUE THREAD

**Issue by klaypigeon** [mickem/nscp#232] opened 2015-12-30 17:19 UTC
I am experiencing this periodically. Currently I have about 700 servers running nsclient. Periodically when I restart the agent via the services console the agent will terminate, but not entirely. It will leave behind the PID and port bindings which prevent the agent from functioning when it restarts. Rather it functions fine locally, but cannot be queried remotely. I am using .4.3.143 with OpsView Pro. I have tried everything to close the connections (tcpview) or kill the pids but everything basically says the process is non-existent so no action can be taken. The only remedy I have found is to reboot the systems. Currently I am looking at the issue on one of my domain controllers and am not thrilled about needing to reboot. Are you aware of anyway to fix this issue or kill the pid? I am wondering if it is a child process that is keeping stuff locked up but process explorer shows me nothing.

This may help, but I am not sure what else I can give you. nsclient was running as 2204.

PS C:\Windows\system32> netstat -anob | select-string "listening" | Select-String "2204"

  TCP    0.0.0.0:5666           0.0.0.0:0              LISTENING       2204
  TCP    0.0.0.0:5666           0.0.0.0:0              LISTENING       2204
  TCP    0.0.0.0:12489          0.0.0.0:0              LISTENING       2204
  TCP    0.0.0.0:12489          0.0.0.0:0              LISTENING       2204
  TCP    [::]:5666              [::]:0                 LISTENING       2204
  TCP    [::]:12489             [::]:0                 LISTENING       2204

PS C:\Windows\system32> taskkill /f /pid 2204
ERROR: The process "2204" not found.

PS C:\Windows\system32> get-service nscp

Status   Name               DisplayName
------   ----               -----------
Stopped  nscp               NSClient++ (x64)

**Comment by willemdh** [comment] 2015-12-31 10:56
I have noticed similar problems with 0.4.1.105. In very rare cases the client crashes and can't be started as 'the port is already in use'. Like you say, the only solution at such a time is reboot the system, which is not easy in some cases for highly critical servers. I was hoping this issue was resolved in later versions.

**Comment by klaypigeon** [comment] 2015-12-31 14:51
Apparently not so rare in my case. I went 4/4 yesterday. All 4 systems required rebooting. 3 of them were domain controllers which was not very well received.

**Comment by klaypigeon** [comment] 2015-12-31 18:15
We are making some progress, but it still seems like a bug. It definitely appears that nsclient++ is not killing off all of it's children. I have found now that plugins and event handlers are both leaving children active with now non-existent parents. When those child processes are manually terminated and nsclient can be correctly restarted all is well. 

This brings another issue to light, when nsclient restarts, why is it willing to start if there are already port bindings in a listen state on 5666? 
 TCP    [::]:5666              [::]:0                 LISTENING       1380
[System] - Failed, holding ports open
 TCP    [::]:5666              [::]:0                 LISTENING       120792
[nscp.exe] - Service restart creates this, which cannot be queried.

Here is a screen shot of one I just found as well, this process was found to have died and so was relaunched by an event handler. Nsclient becomes its parent. Nsclient restarts at some later time  and cf-serverd becomes an orphan but forces some part of nsclient to keep the ports open.

![image](https://cloud.githubusercontent.com/assets/11639938/12067002/162a1ee0-afc0-11e5-9dff-e52a7825f7d8.png)

**Comment by mickem** [comment] 2016-01-19 06:58
This has been popping up for years, I have yet to be able to simulate it so if someone can come up with a way to force the issue to happen I would very much like to fix it but it is difficult to fix things which when I cannot reproduce them...

**Comment by willemdh** [comment] 2016-01-19 07:57
it's definitely very hard to reproduce. I'm seeing this issue once or twice a week on one of 500 servers. I've seen it on different os'es. 
it would be nice to have a workaround which would solve the issue without us having to restart the server. Any ideas / tips? I remember I even tried re-installing the NSClient agent which also didn't help.

**Comment by klaypigeon** [comment] 2016-01-19 20:58
mickem, can you try this scenario. I have found this works to reproduce. Nsclient version  .4.3.143

A common occurrence where the issue would happen is with an eventhandler.  You might run an eventhandler to restart a process that has crashed.  The process may be a service that is supposed to run forever.  If you stop and start the NSClient++ service, the child pid eventhandler would still be running.  Once you stop the service, you can see that the old pid becomes non-existant but still running if you check with Sysinternals tcpview.exe.  The non-existant pid still holds the port open and restarting the service does not fix the issue.  The only way to free up the port is to kill all children of the last running NSClient++ service.

Here is how you reproduce the issue.

Add a new NRPE script:

[/settings/external scripts/scripts]
eh_test=scripts\test.bat

test.bat contents:
start ping 127.0.0.1 -n 99999 > nul

(Re)start NSClient++ service

Test that it is working:
# ./check_nrpe -H <host>
I (0.4.3.143 2015-04-29) seem to be doing fine...

Run your eventhandler: 
# ./check_nrpe -H <host> -c eh_test

C:\Program Files\NSClient++>start ping 127.0.0.1 -n 99999  1>nul|

Open Task Manager and observe that PING.EXE is running.

Restart the NSClient++ service

Examine with tcpview.exe that non-existant pid is listening on port 5666

Test the agent:
# ./check_nrpe -H <host>
CHECK_NRPE: Socket timeout after 10 seconds.

**Comment by mickem** [comment] 2016-01-20 11:07
If it is a timeout issue then configuring timeouts correctly should help right?
i.e. externalscripts timeout < nrpe server timeouts.

But I will see if I can recreate it using this method...

// Michael Medin

**Comment by klaypigeon** [comment] 2016-01-20 14:04
Is it possible event handlers are inheriting descriptors from nsc++? Forgive my syntax as I don't code c++. But it seems like child processes are being passed the tcp ports.

**Comment by klaypigeon** [comment] 2016-01-20 14:12
Relevant??

The problem can be caused if the dead process has started one or more child processes. If

`BOOL WINAPI CreateProcess(

_In_opt_    LPCTSTR               lpApplicationName,

_Inout_opt_ LPTSTR                lpCommandLine,

_In_opt_    LPSECURITY_ATTRIBUTES lpProcessAttributes,

_In_opt_    LPSECURITY_ATTRIBUTES lpThreadAttributes,

_In_        BOOL                  bInheritHandles,

_In_        DWORD                 dwCreationFlags,

_In_opt_    LPVOID                lpEnvironment,

_In_opt_    LPCTSTR               lpCurrentDirectory,

_In_        LPSTARTUPINFO         lpStartupInfo,

_Out_       LPPROCESS_INFORMATION lpProcessInformation

);`
was used to start a child process, it depends on the value of inherit handles, so with

bInheritHandles = false 
Windows will not block the port if the parent process is stopped and the client process is still running.

**Comment by klaypigeon** [comment] 2016-02-22 21:41
Any movement on this?

**Comment by mickem** [comment] 2016-03-07 21:30
This is non trivial to fix.
Problem is that I need to inherit handles to communicate with the scripts.

There are a few ways to work around this, the simplest one using the WSA_FLAG_NO_HANDLE_INHERIT flag which is only supported on windows 7 sp1.
Problem though is that boost::asio which I use does not support that flag which makes it difficult to add.

**Comment by duncs** [comment] 2016-03-08 14:46
> Problem is that I need to inherit handles to communicate with the scripts.

Fair enough, but do you need the children to inherit all the handles the parent passes on?  Can you not just close any unrequired handles as the first step?  For example, do you need a handle to port 5666 open in the children?   I would have thought that should only stay with the parent.

**Comment by klaypigeon** [comment] 2016-03-08 16:24
Interesting code dilemma, but one that creates a situation requiring a server reboot is pretty serious (if the child process cannot be identified). Perhaps for now you can suggest the best way to work around this issue. 

Here is a for instance situation. Event handler calls eh_cf-serverd.ps1 to be run by nsclient.

eh_cf-serverd.ps1
```
stop-process -name cf-serverd -force
start-process -nonewwindow -filepath "c:\program files\cfengine\bin\cf-agent.exe" -argumentlist "-K -D validated_updates_ready -f update.cf"
```
Powershell and cf-agent terminate.
The cf-agent command causes cf-serverd.exe to start, but it receives the port inheritance as well and then if we restart nscp, it is unable to gain control of it's port. In this case, what would you suggest might be our best bet?

**Comment by Daniel-Beardsmore** [comment] 2016-03-09 10:00
I’m seeing the same issue — check_openmanage.exe hangs, but only ever during an NSClient++ service restart, so the TCP sockets are not freed. My guess is that check_openmanage.exe gets confused when the parent process unexpectedly disappears, and it then “forgets” to exit. No such hangs appear to ever occur the rest of the time — this problem _appears_ to be specifically triggered by an NSClient++ restart. (I’m not 100% sure, but it’s only happened twice so far, in the week and a half since I’ve started running external scripts.)

When NSClient++ receives a Windows service restart/exit/pause request, does it actually allow any time for currently running scripts to terminate?

Windows is very forgiving about services or the system being busy during service control requests, so how viable is it for it to have a timeout (say, 20 seconds) within which, after a service restart/exit/pause request is received, nscp refuses any new requests (“UNKNOWN NSClient++ service is being stopped/restarted/paused”) but allows time for the existing checks to complete before complying with the request?

It may not solve all the causes of this issue, but it may solve some of them.

Just a thought.

**Comment by mickem** [comment] 2016-03-11 08:15
I was under the impression that the workaround I added to kill processes on exit would help with the problem "unless it is intentional".

But let me reiterate so I am sure we have the same understanding of the issue:

* NSClient++ listens to a port.
* You run a check command.
* NSClient++ runs an external script which "runs forever"
* NSClient++ stops and the port is "locked"
* NSClient++ cannot be started as the port is blocked (by the process which is "running forever")

So the solution/workaround would be "don't run things that run forever".
I.e. use "start" in your script to fork of a new process or something like that?
Running queries "forever" is a very very bad idea from an NSClient++ perspective as you will starve resource eventually. So "fixing the handle issue" would only cause other issues.
One option would be to add a flag to the process to "just fork it and not care about it".

## Solution for normal cases
So for the normal case when an external script is running during restart the fix I already implemented would fix that. I.e. when NSClient++ exits it will terminate all running commands.

## Solution for exotic cases
For other cases when you for instance fork of an even handler which runs forever this would not help as  you would run into other issues. Then the solution would be to change how the process is forked so NSClient++ stops following the process.

## Background
Some background on the issue: http://stackoverflow.com/questions/12058911/can-tcp-socket-handles-be-set-not-inheritable
The reason I cannot simply "not inherit handles" is that I need to read from the process to get the output which is done through handles.

// Michael Medin

**Comment by Daniel-Beardsmore** [comment] 2016-03-11 08:23
In my case, the external script (check_openmanage.exe) should execute and exit within a few seconds. To be completely honest I don‘t know if these hung processes broke when NSClient++ exited, or had crashed at some point earlier in time, and had become forgotten.

**Comment by klaypigeon** [comment] 2016-03-16 19:57
Not 100 % sure we are on the same page as the command I execute via nsc does not run forever. It does spawn another process that runs forever though.
In the case I stated above.
1. nsc launches powershell to execute a command cf-agent
2. cf-agent process spawns cf-serverd process
3. **powershell and cf-agent terminate**
4. cf-serverd continues to run as it should, but also has the inheritance. 

Sounds like basically you are saying "works as designed" and I need to find a way to execute a command from an event handler that breaks inheritance. I will play around and see if I can come up with a situational workaround that doesn't involve killing processes off.

**Comment by mickem** [comment] 2016-03-16 22:09
Well, the question is how to resolve the issue.
For "runs forever" we probably need a better solution.

I can think of two:
1. Create a wrapper command which creates a "child" and forks without handles:
```
[/settings/external scripts/scripts]
check_background = run_bg scripts\check_60s.bat
```
2. An option to "not fork with handles" this means we "wont be able to fetch the result" from the command. And thus the return will never be by the script.
```
[/settings/external scripts/scripts/check_background]
command = run_bg scripts\check_60s.bat
capture output = false
```

The upside of option 1 is that you can place the "run_bg" in your script and thus decide "when" to do it.
The downside is that you get more complicate commands.
The downside of option 2 is that you cant return any data from your command i.e. you check cannot check anything.

**Comment by mickem** [comment] 2016-03-16 22:10
Just to verify that this is the issue though I did a bit of an experiment:

First I created a scheduled task which runs notepad:
```
schtasks /Create /TN nscp_test /TR c:\Windows\notepad.exe /sc ONCE /ST 00:00
```

Then I created two scripts:
1. check_fork_sched.bat
```
@schtasks /run /tn nscp_test
```

2. check_fork_start.bat
```
start notepad.exe
```

Then I added the scripts and enabled extscr and nrpe:
```
nscp ext-scr add --script scripts\check_fork_start.bat
nscp ext-scr add --script scripts\check_fork_sched.bat
nscp ext-scr install
nscp nrpe install --allowed-hosts 192.168.0.1,127.0.0.1,::1
```

Finally run the first command via NRPE:

```
mickem@felix:~$ /usr/lib/nagios/plugins/check_nrpe -H 192.168.0.201 -c check_start
```
Now: restarting NSClient++ means it will not listen to the NRPE port.
Closing notepad and then restarting NSClient++ works as expected (i.e. it listens)

Same thing with the scheduled task:
```
mickem@felix:~$ /usr/lib/nagios/plugins/check_nrpe -H 192.168.0.201 -c check_fork_sched
```
Now restarting NSClient++ works as expected regardless of whether I close notepad or not.

**Closed** 2016-04-11 18:01 UTC
Labels: bug

**Comment by mickem** [comment] 2016-04-11 18:05
I have added a flag to capture output=false flag you can add to disable output capture and relinquish control of the executed process. This means timeouts are not in effect it also means we do not inherit handles.
I.e. the command is "forked" and ignored.

```
[/settings/external scripts/scripts/notepad]
capture output=false
command=notepad.exe
display=true
```

**Comment by gbpullen** [comment] 2016-12-09 17:04
It looks there has been a fix for this issue available for some time now.  Any word from the user community on how effective the fix has been in resolving the issue?  What would be the best release to start testing?

Thank you!

**Comment by gbpullen** [comment] 2016-12-20 17:43
I tested NSClient release 0.5.0.62 and it seems the change works as described.  But the since the 'capture output = false' flag does not allow the check script to return an exit code or message to Nagios that is not an option that we can use.    

Is this the only fix for the issue of a defunct NSClient process retaining the ports?  Does this fix have any effect or work without the 'capture output = false' flag?

**Comment by gbpullen** [comment] 2016-12-23 16:37
Thanks Michael!

Do you have an issue number or link for “killing processes when exiting”  fix you mentioned.

Regards,
Gene

**Comment by mickem** [comment] 2016-12-24 19:30
Not sure what you mean by issue number/link.

The code change can be found here: https://github.com/mickem/nscp/commit/52b1231cd7b7882dbbd0f571a25de8ac3b3ced3c

// Michael Medin

**Comment by gbpullen** [comment] 2017-01-03 15:49
Michael,
This is what I was looking for. Information on when the code change was made and what release level I need to test.

Thank you sir!

Regards, Gene
