### ISSUE TITLE
check_eventlog with status output like CRITICAL: ??? (???)

### ISSUE THREAD

**Issue by mkop5** [mickem/nscp#177] opened 2015-09-24 12:29 UTC
One of our users are running an application that sends entries to Windows Eventlog. That application is registered and they let all messages get eventid 0.

If you execute a check like this:
/opt/plugins/check_nrpe -s -H win-host -c check_eventlog -a file=application  "warning=count > 1" "critical=count > 1"  "filter=written gt -10m AND source like 'GHF001' AND message like 'initialized'" unique 'top-syntax=${status}: ${list}' 'detail-syntax=%(source): %(message)'

The output becomes like this:
CRITICAL: GHF001: (???)

I know that the event is in the eventlog on the windows server and there you can read the message and it's also readable if one exports the event(s) to xml.

I suspect that the "message" comes endcoded in a way NSClient++ can not handle. If I try to monitor a "standard microsoft" message in the event log there is no such problems, all looks as it should.

Is this anything you have seen before and know what it is?

**Comment by mkop5** [comment] 2015-10-20 13:38
Now I have been able to reproduce this. I did reproduce it on a Windows 2008R2 SP2 with NSClient++ 0.4.3.147.

First a test with check_nrpe:
`/opt/plugins/check_nrpe -s -H 192.168.1.136 -c check_eventlog -a file=application  "warning=count > 25" "critical=count > 40"  "filter=source like 'LoadPerf' AND written gt -2000s" unique 'top-syntax=${status}: ${list}'
OK: Application Microsoft-Windows-LoadPerf (Performance counters for the WmiApRpl (WmiApRpl) service were loaded successfully. The Record Data in the data section contains the new index values assigned to this service.), Application Microsoft-Windows-LoadPerf (Performance counters for the WmiApRpl (WmiApRpl) service were removed successfully. The Record Data contains the new values of the system Last Counter and Last Help registry entries.)|'count'=2;25;40`

Then I cleared the application log.

I'm not used to work with Power Shell and windows scripting but I managed to add events to the event logs with a Power Shell line looking like this:
`Write-EventLog -EventId 1000 -LogName Application -Message "Gurka" -Source LoadPerf -Category 10 -ComputerName mk-win2k8r2 -EntryType Error`
I executed the line above once:

Now checking the the host with check_nrpe like this:
`./check_nrpe -s -H 192.168.1.136 -c check_eventlog -a file=application  "warning=count > 25" "critical=count > 40"  "filter=source like 'LoadPerf' AND written gt -1150s" unique 'top-syntax=${status}: ${list}'
OK: Application Microsoft-Windows-LoadPerf (??)|'count'=1;25;40`

**Comment by mickem** [comment] 2015-11-29 08:42
I have looked into this and the problem is that the message requires multiple strings and only one is provided thus it is "impossible" to render the message (via the API).
I am guessing event viewer is cheating somehow rendering it themselves.

I have in latest 0.5.0 build provided a slightly improved error message:

    check_eventlog file=application "warning=count > 25" "critical=count > 40" "filter=source like 'LoadPerf' AND written gt -2000s" unique "top-syntax=${status}: ${list}"
    D   eventlog Failed to format eventlog record: ID=1000: failed to lookup error code: 15029 (reason: 87)
    D   eventlog Error: Failed to evaluate message: Invalidly formatted eventlog message for: failed to lookup error code: 15029 (reason: 87)

If you look in eventviewer you can see the same issue presists (albeit slightly more elegant):

    Performance counters for the Gurka (%2) service were loaded successfully. The Record Data in the data section contains the new index values assigned to this service.

The %2 is where the second string value should have been.

So I am inclined to close this as I would rather not recreate the eventlog rendering functionality. I had that in 0.3.9 and it was rather messy and buggy.

**Comment by mickem** [comment] 2015-12-06 05:55
can we close this ?

**Comment by mickem** [comment] 2015-12-09 10:50
Please reopen/comment on this if you have a case when the formatting is not working as expected (i.e. when the arguments are there but we get the error)

**Comment by mkop5** [comment] 2015-12-09 10:51
With some testing here I found out that if I do create a new source, with a power shell cmd line, and used that one when putting in new events things worked fine. If I then removed that source the output was as described initially here. So I guess that it's the fact that the source was not available was the problem, seem from my "user perspective" at least :)

**Closed by mickem** 2015-12-09 10:51 UTC
Labels: wontfix

**Comment by mkop5** [comment] 2015-12-09 10:52
Haha... you just closed it while I was typing in this message. I was about to sugest the same thing; close the case and I'll reopen it if necessary.

**Comment by mickem** [comment] 2015-12-09 11:00
Yes indeed if the source does not exists there is no formatting string and the message cannot be formatted (via the API)
