### ISSUE TITLE
CHECK_NRPE: Invalid packet type received from server

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#83] opened 2015-01-17 09:34 UTC
Hello,

I upgraded to 0.4.3.88 yesterday on a WIndows 2012 R2. Did some tests today and I seem to have multiple Powershell scripts that are failing with the message "CHECK_NRPE: Invalid packet type received from server." These work fine on 0.4.1.105 and older Windows versions.
When I execute the scripts locally on the server they work fine. 
I did an nscp test and got multiple errors, mostly because nsclient.log cannot be found (and indeed it didn't exist)

C:\Program Files\NSClient++>nscp test 
L     client Module: CommandClient
C:\Program Files\NSClient++\nsclient.log could not be opened, Discarding: message: Module: CommandClient
L     client Command:

After doing some tests, it seems I only get the error when the output is longer. Executing a Powershell script with a short 'write-host' output seems to work fine. From the moment the output is longer (not sure exactly how long) I seem to get "CHECK_NRPE: Invalid packet type received from server"

'''[/settings/NRPE/server]

; ENABLE SSL ENCRYPTION - This option controls if SSL should be enabled.
use ssl = 1

; COMMAND ALLOW NASTY META CHARS - This option determines whether or not the we will allow clients to specify nasty (as in |`&><'"\[]{}) characters in arguments.
allow nasty characters = 1

; COMMAND ARGUMENT PROCESSING - This option determines whether or not the we will allow clients to specify arguments to commands that are executed.
allow arguments = 1

; PORT NUMBER - Port to use for NRPE.
port = 5666

; ALLOW INSECURE CHIPHERS and ENCRYPTION - Only enable this if you are using legacy check_nrpe client.
insecure = true

; VERIFY MODE - Comma separated list of verification flags to set on the SSL socket.  
verify mode = none

; EXTENDED RESPONSE - Send more then 1 return packet to allow response to go beyond payload size (requires modified client).
extended response = 0

timeout = 300
'''
Tried setting 'extended response to 0 and 1, but makes no difference. Is there something else I'm forgetting?

Thanks.

Willem

**Comment by mathieuchateau** [comment] 2015-01-17 09:36
Hello,

Did you start your cmd with run as administrator ? else nscp can't write
the nsclient.log as it's in program files



Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-17 10:34 GMT+01:00 willemdh <notifications@github.com>:

**Comment by willemdh** [comment] 2015-01-17 09:40
Ha nscp test seems to work better. Hate uac.. Thanks. ANy idea bout the "CHECK_NRPE: Invalid packet type received from server"?

**Comment by mathieuchateau** [comment] 2015-01-17 09:44
If you know for sure one script output that fails, could you send an
example ?



Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-17 10:40 GMT+01:00 willemdh <notifications@github.com>:

**Comment by willemdh** [comment] 2015-01-17 09:55
Well, seems I found a way to make it work. When I let the nscp service run with an account with admin permissions, it seems to work. 
An example of a script => http://exchange.nagios.org/directory/Plugins/Operating-Systems/Windows/NRPE/Check-Microsoft-Windows-Scheduled-Tasks/details

So nscp running as localsystem on W2012R2:
CHECK_NRPE: Invalid packet type received from server:
 /usr/local/nagios/libexec/check_nrpe -H testserver2012 -t 60 -p 5666 -c check_ms_win_tasks -a '-H Localhost' 

WORKS: 
/usr/local/nagios/libexec/check_nrpe -H testserver2012  -t 60 -p 5666 -c check_ms_win_tasks -a '-H Localhost -EF Microsoft'

On other servers I have (2008 R2) the two above examples work fien with localsystem.

Grtz and thanks for your time. The issue might be related to WIndows 2012 R2 and not NSClient 0.4.3.88 as we only recently acquired 2012 R2 licenses.

Grtz

**Comment by mathieuchateau** [comment] 2015-01-17 10:01
looks weird.
I have mainly 2012R2 servers on my side.
nsclient run with local system, and i successfully monitor scheduled tasks

Why don't you use the builtin feature of nsclient to check tasks ? that's
what i use without issue



Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-17 10:55 GMT+01:00 willemdh <notifications@github.com>:

**Comment by mathieuchateau** [comment] 2015-01-17 10:03
I guess -H localhost make the script connecting as if it was a remote
system. Local system only works on local system, not remote.

Using domain admin is very very bad from security point of view. Any audit
will shoot you down


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-01-17 11:00 GMT+01:00 Mathieu Chateau <mathieu.chateau@lotp.fr>:

**Comment by willemdh** [comment] 2015-01-17 10:05
Because I like my version better :) And the output displays the owner of the failed tasks, will parse exit codes, return perfdata resulting in grapsh which show when tasks are running etc. THis is jsut one example, I have other Powershell script which give similar "CHECK_NRPE: Invalid packet type received from server:" Don't mind -H localhost, it's just sth I pass, as it can do remoting  too, but not in the version on Exchange. (still in test)

**Comment by willemdh** [comment] 2015-01-17 12:59
You can close the issue if you think it has nothing to do with 0.4.3.88. I just did not see this error before. (But i come from 0.4.1.105)

**Comment by mickem** [comment] 2015-01-27 16:13
I think this is due to the "multi package patch" which is default applied...

Maybe I should to disable that for legacy mode?

I will investigate a bit and get back in the next few days...

**Comment by willemdh** [comment] 2015-01-27 16:38
"Maybe I should to disable that for legacy mode?"

I can't answer this question for you Michael, as I have no idea what the multi package patch is, not what legacy mode is. I trust you make the correct decision. 
My Powershell plugin just did no longer seem to work after an upgrade untill I made the service run with local admin account.

**Comment by mickem** [comment] 2015-01-27 18:34
I can confirm this issue and it will be resolved in the next build.

**Comment by mickem** [comment] 2015-01-27 18:45
Just to clearify..

The "multi package patch" is something ton voon created several years ago which allows you to send more then 1024 chars back via NRPE.

With legacy mode I meant the "insecure" old nrpe mode which most are using...

**Comment by willemdh** [comment] 2015-01-27 19:30
Michael,

Thanks for the patch. Yes indeed i'm using the insecure mode. Just read through this:
http://www.medin.name/blog/2012/12/02/securing-nrpe-with-certificate-based-authentication/

Seem interesting. Really. But I'm having my head full of several big projects. Maybe in half a year or so, I'd investigate further. 

Grtz

Willem

**Comment by mickem** [comment] 2015-01-29 19:35
0.4.3.102 should fix this issue, please reopen if issue still persists...

**Closed by mickem** 2015-01-29 19:35 UTC
Labels: bug

**Comment by borgified** [comment] 2015-05-19 22:54
i encountered this issue in version 0.4.3.143 however i was able to get around the issue by piping the STDOUT to a file then retrieving that file later. i verified that the problem occurs when there is too much output by varying the amount of data that would get sent to STDOUT until the problem showed up. i am using legacy mode.
