### ISSUE TITLE
Swedish perfcounter fails

### ISSUE THREAD

**Issue by fmikker** [mickem/nscp#237] opened 2016-01-15 12:01 UTC
When checking a perfcounter with swedish language pack, nsclient can't find the counter.

./check_nrpe -s -H 0.0.0.0 -t 20 -c CheckCounter -a "Counter=\Logisk disk(_Total)\Diskläsningar/s" ShowAll MaxWarn=20 MaxCrit=25
Utdata:
CRIT: Counter not found: \Logisk disk(_Total)\Diskläsningar/s: Den angivna r▒knaren kunde inte hittas. (C0000BB9)

**Comment by mickem** [comment] 2016-01-19 06:44
Given that it is developed in Sweden and Swedish are the only localized ones which I test i much doubt that :)

In this case I would guess the problem is encodings over NRPE.
You can set encoding in nsclient.ini and it has to match the encoding on your linux machine.
This is as the NRPE protocol is limited and does not support encoding data properly.

// Michael Medin

**Comment by mickem** [comment] 2016-01-19 06:46
You can find the docs for encoding here: http://docs.nsclient.org/reference/client/NRPEServer.html#NRPEServer./settings/NRPE/server.encoding

**Comment by mickem** [comment] 2016-03-11 09:03
Closing this, please reopen if you still have issues

**Closed by mickem** 2016-03-11 09:03 UTC
