### ISSUE TITLE
Connection Refused on NSclient newer than 0.4.3.77 (Seems installer does not apply config correctly)

### ISSUE THREAD

**Issue by neonunit** [mickem/nscp#238] opened 2016-01-17 09:30 UTC
Hello everyone,
I have experienced a weird issue trying to install latest NSClient on my Windows machines. No particular reason - just like to keep things up-to-date.
Before that I was using NSCP 0.4.1.73 and the update process went very smoothly.
This time, however, after installing newer NSCP, like 0.4.4.15 or 0.5.0.19, Nagios starts screaming that connection on port 12489 has been refused.
I've looked into it and found that NSCP services newer than 0.4.3.77 seem not to open this particular port.
That's how it looks like on NSClient 0.4.3.77:

![old](https://cloud.githubusercontent.com/assets/16742059/12376769/e7bf21a2-bd04-11e5-9177-e4bb43d5c7a0.jpg)

That's how it looks like on NSClient 0.5.0.19:

![new](https://cloud.githubusercontent.com/assets/16742059/12376773/fd66d4d2-bd04-11e5-94aa-7f24282ac92c.jpg)

What is the reason for this? Except entering my Nagios server's IP address and password during the installation process I have NOT altered the NSCP config file in any way.

**Comment by neonunit** [comment] 2016-01-17 09:38
Solved! :D 
It seems that this new installer type or whatever it is doesn't apply these two lines into the config file:
allowed hosts =
NSClientServer = 1
Added them, restarted the service and it works fine now.
That's just weird, why would the installer ask for the monitoring server's IP address if it doesn't add it to the config file?

**Comment by mickem** [comment] 2016-01-19 20:26
Sounds like a bug... It should absolutely add the correct config.

**Comment by mickem** [comment] 2016-01-27 19:33
Next 0.5.0.x build will hopefully fix this issue, if not let me know...
What I do now is kill all running processes (scripts) when NSClient++ exits

**Comment by Remnence** [comment] 2016-02-16 20:47
I was having the same issue. I finally found the cause. The modules folder isn't getting fully populated in the newer installers. I only had 22/31 dll files, NSClientServer.dll being one of the missing files. I copied it from the zip and restarted the service and it now works.

**Comment by mickem** [comment] 2016-02-17 18:30
The DLLs can be toggled in the installer...

**Comment by Remnence** [comment] 2016-02-17 18:51
Yeah, I followed the guide at https://docs.nsclient.org/0.4.4/tutorial/core/index.html#deploy-massively-manage

And I now realized that they removed those DLLs in the install script. Everything seems to be working now.

**Comment by mickem** [comment] 2016-03-11 19:29
Guess we can close this, if you still have issues pleas reopen...

**Comment by JonWolberg** [comment] 2017-08-02 17:36
I am still seeing this issue on 0.5.0.62 on a Windows 10 machine. I should note that the issue is present on the 64bit build but not present on the 32bit build.  0.4.1.73 works perfectly fine.

**Comment by mickem** [comment] 2017-08-20 15:45
Do you have a reproducible scenario?

**Comment by mickem** [comment] 2018-03-30 11:33
Please reopen this with a detailed explanation of the issue is (unless it is a missing config key) and how to reproduce it.
Please include the generated config, and what the expected config should be as well as any install switches applied.

**Closed by mickem** 2018-03-30 11:33 UTC
Labels: bug
