### ISSUE TITLE
NSC Web - getsockopt: connection refused with large amount of checks

### ISSUE THREAD

**Issue by ainsey11** [mickem/nscp#444] opened 2017-07-17 10:19 UTC
Morning, 

we have swapped to using the WEBServer for nagios to talk to nsclient, but we've noticed that hosts with a larger number of checks assigned to them often come back with an error as follows : 

UNKNOWN: Get https://<servername>:8443/query/<check>: dial tcp <ip>:8443: getsockopt: connection refused

This is intermittent across all the hosts with this,  we are running version 0.5.1.31x64 on Server 2012 R2. number of checks varies per host, but anything more than 30 seems to be susceptible to the problem - the ones we notice it most on have 50+ checks

There is nothing in the nsclient log on the host itself, 

Thanks!

Ainsey

**Comment by mintsoft** [comment] 2017-07-18 08:49
Hello,

We are also having this problem. We've converted all of our nrpe checks to use the webserver and `check_nsc_web` that's bundled with OMD 2.40. We're finding that we get periods of results like:
```
server001;CPU Load;UNKNOWN;HARD;5;UNKNOWN: Get https://server001:8443/query/alias_cpu: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
We're also on 0.5.1.31, and when we were using NRPE we didn't seem to have this problem with the checks that we've got. The nagios server and the server being checked are connected by a single switch that's way below its capacity so it's not a network timeout and the `check_nt` checks don't experience this issue and when the servers are throwing this error, they're not especially loaded (i.e. ~ 10% CPU consumed). 

There's also nothing in the log for us, is there a way to get some debugging information about this somehow?

Thanks,
Rob

**Comment by mintsoft** [comment] 2017-07-18 08:51
@mickem Is increasing https://docs.nsclient.org/reference/generic/WEBServer/#thread-pool a good idea to fix this or is it more likely that'll lead to different issues?

**Comment by mintsoft** [comment] 2017-07-19 11:48
I've just tried running NSclient with 
```
[/settings/log]
file name = nsclient.log
level = debug
```

In hope there'd be something useful in the logs when it happens, but there isn't any indication of any problem; it just basically looks like the WEBServer is totally unreliable in 0.5.1.31 in some sort of invisible way

**Comment by ainsey11** [comment] 2017-07-20 11:10
I've done some further investigation on the issue, 

I ran 8 consecutive loops, running the alias_cpu check against one of our servers using the nscWEB setup,
I enabled --verbose on the check and I just get the error mentioned in the original issue comment, 

Increasing the thread pool option does not seem to have any effect on the problem, I changed it to 40 on one of the servers and it exhibits the exact same behavior as when the value is set to default (10)

It looks as if it isn't load related, as @mintsoft says, the WEBServer just seems completey unreliable in 0.5.1.31

**Comment by mintsoft** [comment] 2017-07-20 12:16
I'm a little confused around the implementation of the webserver; comparing it to the NRPE server there are a few locking cases (`metric-handler` for example); from what I can see, it locks using the `boost:timed_mutex` (https://github.com/mickem/nscp/blob/master/modules/WEBServer/WEBServer.cpp#L831) however `unlock()` is never called? So is it depending on the timeout to synchronize the threads?

**Comment by mintsoft** [comment] 2017-07-24 08:52
I've also just reproduced it using curl in order to exonerate `check_nsc_web` like:
```bash
while curl --header 'Password: blah' --insecure --include https://servername:8443/query/alias_disk; do echo""; sleep 30; done
``` 
which will run until the command fails (which I've just seen). The output from curl wasn't incredibly useful, however it was `curl: (7) Failed to connect to servername port 8443: Connection refused`

![curlreproduced](https://user-images.githubusercontent.com/978048/28515484-ba106d96-7055-11e7-927c-f7c418fdffa6.png)

I can run it with the debug flag to see if I can get more information however it looks like NSClient++ is refusing the TCP connection itself from that error.

**Comment by mintsoft** [comment] 2017-07-24 10:50
We've had to revert back to using `check_nrpe` as it's far more reliable than the WEB server it seems. If there's any diagnostic information that could be helpful I'd be happy to grab it @mickem

**Comment by biscuitNinja** [comment] 2017-07-24 11:02
This also seems to be an issue for us to. It seems possible to reproduce.
Our longest running check on one of the worst affected servers take ~2 seconds.
Run it continuously, check time remains fairly constant. Run the check in parallel (8x) and initially the check execution time increases and once it breaches just under 10 seconds, I see 

`request cancelled (Client Timeout exceeded while awaiting headers)`

returned from check_nsc_web. Continuing to run the check in parallel then starts to ellicit 

`getsockopt: connection refused`

Whilst hammering a client with these checks, all the other checks run via check_nsc_web increase in execution time and then start to throw similar errors. It appears there is a definite bottleneck in NSClient++ web that makes it more restrictive relative to using NRPE, at least in respect to volume of checks.

**Comment by ainsey11** [comment] 2017-07-26 09:46
I've reverted to check_nrpe on our servers now too @mickem - it seems as though the issue is prevalant despite of load, one of our boxes in "idle" flagged a connection refused.

**Comment by mickem** [comment] 2017-07-28 10:35
What is large amount of checks?

Using the following script to simulate load I managed to get 30r/s on my computer this would with a check frequency of every 30s yield 900 checks...

Now if you check every second (which is I guess not that common) you get (obviously) 30 check which is the number your quoting so that is what I am guessing....

In that scenario I would probably advocate bundling more then one check in each call.
I will investigate if it is possible to configure the webserver to increase the number of connections...

```
import Queue
import threading
import urllib2
import ssl
import json
import time

#
# Configuration
#
PASSWORD = "MYPASSWORD"
URL = "https://localhost:8443/query/check_cpu"
THREADS = 32
COUNT_PER_THREAD = 50

ctx = ssl.create_default_context()
ctx.check_hostname = False
ctx.verify_mode = ssl.CERT_NONE


def get_url(q, url):
    for x in xrange(COUNT_PER_THREAD):
        try:
            req = urllib2.Request(URL)
            req.add_header('password', PASSWORD)
            resp = urllib2.urlopen(req, context=ctx)
            data = json.loads(resp.read())
            msg = data["payload"][0]["lines"][0]["message"]
            q.put(msg)
        except Exception as e:
            q.put("%s"%e)

q = Queue.Queue()

threads = []
for u in xrange(THREADS):
    t = threading.Thread(target=get_url, args = (q,u))
    t.daemon = True
    threads.append(t)

start = time.time()
for t in threads:
    t.start()

for t in threads:
    t.join()
end = time.time()

time = end-start
sz = q.qsize()

last = ''
cnt = 0
while not q.empty():
    msg = q.get()
    cnt = cnt + 1
    if msg != last:
        print "(%d): %s"%(cnt, msg)
        last = msg
        cnt = 0
print "(%d): %s"%(cnt, last)

print "Time spent: %s calls in %d seconds %dr/s"%(sz, time, sz/time)
```

**Comment by biscuitNinja** [comment] 2017-07-28 10:50
Hi Mickem,
Can I suggest you retry with a check that has some duration - check_cpu returns in under 100ms.
Thanks
.bn

**Comment by mintsoft** [comment] 2017-07-28 11:09
@mickem I've just tested again here but using alias_disk. Using 12 concurrent loops without sleeps (`while curl --header 'Password: blah' --insecure --include https://servername:8443/query/alias_disk; do echo""; done`) and it broke in about 5 minutes or so. I wonder if as @biscuitNinja said, overlapping instances of checks being executed is what causes the problem

**Comment by mintsoft** [comment] 2017-07-28 11:42
OK so I struggled to reproduce this using `check_cpu`, however doing the following works,
define an external script command that takes some time (I used the attached:  
[check_ping2.zip](https://github.com/mickem/nscp/files/1182865/check_ping2.zip)) and used nsclient.ini like:
```
[/settings/default]
password = password
allowed hosts = 127.0.0.1,192.168.1.10

[/settings/NRPE/server]
verify mode = none
insecure = true

[/settings/external scripts/alias]
alias_cpu = checkCPU warn=85 crit=95 time=1m
alias_cpu_ex = checkCPU warn=$ARG1$ crit=$ARG2$ time=5m time=1m time=30s
alias_disk = CheckDriveSize MinWarn=10% MinCrit=5% CheckAll FilterType=FIXED perf-unit=G
check_ok = CheckOK Everything is fine!

[/settings/external scripts]
;command timeout = 5

[/settings/external scripts/scripts]
robtest_sleep=scripts\check_ping2.bat localhost

; in flight - TODO
[/modules]

; Undocumented key
CheckExternalScripts = enabled

; Undocumented key
CheckHelpers = disabled

; Undocumented key
CheckEventLog = disabled

; Undocumented key
CheckNSCP = disabled

; Undocumented key
CheckDisk = enabled

; Undocumented key
CheckSystem = disabled

; Undocumented key
WEBServer = enabled

; Undocumented key
NRPEServer = enabled
```

Using curl, when I have 8 of the loops running I can't start a 9th as it never succeeds:
![nsc_web_blocked](https://user-images.githubusercontent.com/978048/28715888-277c068a-7392-11e7-8a9b-d75bcd238c76.png)

Compare with nrpe (this is 25 running concurrently without issue):
![nrpe_ploughing_on](https://user-images.githubusercontent.com/978048/28715891-2acaa2f6-7392-11e7-9c25-8efcd858bbb3.png)

**Comment by mickem** [comment] 2017-07-28 13:54
I have looked a bit at the impl. of the moongose c++ wrapper I use and I can confirm that it is effectively single threaded meaning you are all right... a long running process will effectively hang the web server.

This is unfortunately a design issue so in other words not easy to fix...
I will probably rewrite the wrapper completely since it is abandoneware by the original author.

But alas this is not something done in 5 minutes...

**Comment by mickem** [comment] 2017-09-17 19:26
Some quick updates...
I have just created a new moongose wrapper which is multi threaded, so expect a build out in a few days which fixes this...

**Comment by mintsoft** [comment] 2017-09-17 19:30
Awesome @mickem I'll definitely try it out when it's available

**Comment by mickem** [comment] 2017-10-06 03:39
Closing this as we now have a second build of the new webserver open, reopen if you still have issues with 0.5.2 builds...

**Comment by mickem** [comment] 2017-10-06 03:40
Latest build can (BTW) be found here https://github.com/mickem/nscp/releases/tag/0.5.2.6

**Closed by mickem** 2017-10-06 03:39 UTC
Labels: bug
