### ISSUE TITLE
NSCLient 0.4.3.131 Realtime/filters filter expression is not working

### ISSUE THREAD

**Issue by user872** [mickem/nscp#120] opened 2015-03-12 15:45 UTC
from my ini:
[/settings/eventlog/real-time/filters/eventlog_error]
filter=id=100
target=FILE,CACHE
severity=WARNING

[/settings/eventlog/real-time/filters/eventlog_error2]
filter=level = 'error'
target=FILE,CACHE
severity=CRITICAL

if i execute on a Windows Client:
eventcreate /T ERROR /ID 100 /L APPLICATION /D TEST

a event ist created ..the level of this event is shown as 2 = error(german Client shows 'Fehler') in the eventlog

but the filter eventlog_error2 will not match this

if a event is generated with level 3 (Warning) then the filter eventlog_error2 will match.....

I tried to filter=level = 2 to go on the value shown in the windows eventlog xml msgs, but this also does not work....

-----------------------------------------------------

Also it is not possible for me to insert events with the nscp client if you run nscp eventlog it shows command not found... so i was using eventcreate from the OS...

**Comment by mickem** [comment] 2015-03-24 22:02
I can confirm this, the problem is the real time thread is using the "old" API which is pretty bad considering it is rather limited but since the machine supports the new a lot of the logic slots in on the new side, IN essence I need to redo this s a bit...

A work around is to use the numerical value:
```
...
filter=level = 1
```

**Comment by mickem** [comment] 2016-03-20 06:30
This has been fixed in 0.5.0

**Closed by mickem** 2016-03-20 06:30 UTC
Labels: bug
