### ISSUE TITLE
checkcpu does not show perfdata for all cpus

### ISSUE THREAD

**Issue by mkop5** [mickem/nscp#339] opened 2016-10-28 08:51 UTC
Let's say I have a windows server with 8 cpus and then I want to check them with the following command:
check_nrpe -s -H win-server -c CheckCPU -a ShowAll=long MaxWarn=80% MaxCrit=90%

Then I will get the following output:
[user@monitor-srv $] # With NSClient++ 0.5.0.62:
```
[user@monitor-srv $] ./check_nrpe -s -H win-server -c CheckCPU -a ShowAll=long MaxWarn=80% MaxCrit=90%
OK: CPU Load: 5m: average load 1%, 5m: average load 0%, 5m: average load 0%, 5m: average load 0%, 5m: average load 0%, 1m: average load 4%, 1m: average load 2%, 1m: average load 1%, 1m: average load 1%, 1m: average load 2%, 5s: average load 0%, 5s: average load 0%, 5s: average load 0%, 5s: average load 0%, 5s: average load 0%|'core 0 5m'=1%;80;90 'core 1 5m'=0%;80;90 'core 2 5m'=0%;80;90 'core 3 5m'=0%;80;90 'total 5m'=0%;80;90 'core 0 1m'=4%;80;90 'core 1 1m'=2%;80;90 'core 2 1m'=1%;80;90 'core 3 1m'=1%;80;90 'total 1m'=2%;80;90 'core 0 5s'=0%;80;90 'core 1 5s'=0%;80;90 'core 2 5s'=0%;80;90 'core 3 5s'=0%;80;90 'total 5s'=0%;80;90
```

[user@monitor-srv $] # With NSClient++ 0.4.4.15:
```
[user@monitor-srv $] ./check_nrpe -s -H win-server -c CheckCPU -a ShowAll=long MaxWarn=80% MaxCrit=90%
OK: CPU Load: 5m: average load 0%, 1m: average load 0%, 1m: average load 0%, 1m: average load 0%, 1m: average load 0%, 1m: average load 0%, 5s: average load 0%, 5s: average load 0%, 5s: average load 0%, 5s: average load 0%, 5s: average load 0%|'total 5m'=0%;80;90 'core 0 1m'=0%;80;90 'core 1 1m'=0%;80;90 'core 2 1m'=0%;80;90 'core 3 1m'=0%;80;90 'total 1m'=0%;80;90 'core 0 5s'=0%;80;90 'core 1 5s'=0%;80;90 'core 2 5s'=0%;80;90 'core 3 5s'=0%;80;90 'total 5s'=0%;80;90
```

As you can see here the problem isn't really new but the output is different when comparing the two versions above.

**Comment by mickem** [comment] 2016-11-14 19:10
Not 100% sure how CheckCPU is translated (all non underscore commands are translated BTW) but What I get from using check_cpu seems to be all cores?

```
check_cpu filter=none
L        cli OK: OK: CPU load is ok.
L        cli  Performance data: 'core 0 5m'=9%;80;90 'core 1 5m'=6%;80;90 'core 2 5m'=10%;80;90 'core 3 5m'=7%;80;90 'core 4 5m'=12%;80;90 'core 5 5m'=7%;80;90 'core 6 5m'=13%;80;90 'core 7 5m'=7%;80;90 'total 5m'=9%;80;90 'core 0 1m'=9%;80;90 'core 1 1m'=6%;80;90 'core 2 1m'=10%;80;90 'core 3 1m'=6%;80;90 'core 4 1m'=9%;80;90 'core 5 1m'=7%;80;90 'core 6 1m'=11%;80;90 'core 7 1m'=6%;80;90 'total 1m'=8%;80;90 'core 0 5s'=8%;80;90 'core 1 5s'=5%;80;90 'core 2 5s'=8%;80;90 'core 3 5s'=3%;80;90 'core 4 5s'=8%;80;90 'core 5 5s'=5%;80;90 'core 6 5s'=9%;80;90 'core 7 5s'=5%;80;90 'total 5s'=6%;80;90
```

**Comment by mickem** [comment] 2017-02-01 04:53
Any update on this or can we close it?

**Comment by mickem** [comment] 2017-02-05 16:23
please reopen if this is still an issue...

**Closed by mickem** 2017-02-05 16:23 UTC

**Comment by op5-support** [comment] 2017-02-13 13:22
Yes, it's still an issue. Using the following command:
check_nrpe -s -H WIN-HOST -c CheckCPU -a ShowAll=long MaxWarn=80% MaxCrit=90% 

Gives the following result:
OK: CPU Load: 5m: average load 14%, 5m: average load 20%, 5m: average load 11%, 5m: average load 11%, 5m: average load 17%, 5m: average load 10%, 5m: average load 9%, 5m: average load 9%, 5m: average load 13%, 1m: average load 12%, 1m: average load 14%, 1m: average load 8%, 1m: average load 7%, 1m: average load 12%, 1m: average load 7%, 1m: average load 6%, 1m: average load 7%, 1m: average load 9%, 5s: average load 11%, 5s: average load 11%, 5s: average load 7%, 5s: average load 6%, 5s: average load 17%, 5s: average load 8%, 5s: average load 4%, 5s: average load 9%, 5s: average load 9% 

As you can see above, no performance data at all. The NSClient++ version used here is: 0.5.0.62

**Comment by mickem** [comment] 2017-02-13 15:06
And the problem is not related to length? Currently when the payload is to long perfdata is truncated...

**Comment by op5-support** [comment] 2017-02-16 11:55
The strange thing here is that it works with 2 and 4 CPUs but not 1 or 8.

Now we have found out that this command works just fine:
`check_nrpe -s -H WIN-HOST -c check_cpu -a filter=none "warn=load > 80" "crit=load > 90" `
Can you explain why?

**Comment by mickem** [comment] 2017-02-16 12:30
8 cpus could be length as details is about of data...  Best way is to run the command  locally and se of there is a difference as no data is only truncated via nrpe... 

But that does not really explaib the one CPU case unless it has many cores...

**Comment by mickem** [comment] 2017-02-16 12:31
About=a lot...  Apparently Edit dos not work via mobile browser...

**Comment by op5-support** [comment] 2017-02-16 12:39
Let's close this one for now anyway. It seems to be working with the command line I gave you last time here. If new things shows up we'll reopen the case.
