### ISSUE TITLE
INF: Detected crash...

### ISSUE THREAD

**Issue by 00stormy00** [mickem/nscp#304] opened 2016-05-25 10:36 UTC
Hy to all !!

I'm using the nsclient with icinga2 on Windows Server 2008R2  to Server 2012R2
All looks great but on one Server 2008R2 (fully patched) the nsclient++ crash's when icinga2 will start any command.

First time I used nsclient++ Version 0.4.4.19, I also tried nsclient++ Version 0.5.0.45
The problem still exists and is reproducible
A dmp-file is attached

Command and Output:
INF: Detected crash...
INF: Running: "C:\Program Files\NSClient++\reporter.exe" "archive" "C:\Users\sbsadmin\AppData\Local\Temp\0ca2bc6e-78ad-4fe7-babe-367c549424ce.dmp" "NSClient++" "0.5.0.45" "2016-04-15" "C:\Program Files\NSClient++/crash-dumps"
INF: Running: "C:\Program Files\NSClient++\reporter.exe" "restart" "NSCP"
Stopping service.
Starting NSCP

Hope anybody able to help me

cheers
roland

[fd5b23de-dd4d-4145-96e3-832608528b8e.dmp.txt](https://github.com/mickem/nscp/files/281553/fd5b23de-dd4d-4145-96e3-832608528b8e.dmp.txt)
[fd5b23de-dd4d-4145-96e3-832608528b8e.dmp.txt](https://github.com/mickem/nscp/files/281554/fd5b23de-dd4d-4145-96e3-832608528b8e.dmp.txt)

**Comment by mickem** [comment] 2016-05-30 18:18
The dump file is what is needed to analyze not the .txt file.

You can upload it with the following command (assuming you have both the .txt and the .dmp:

```
reporter.exe send fd5b23de-dd4d-4145-96e3-832608528b8e.dmp http://crash.nsclient.org/crash_upload
```

**Comment by 00stormy00** [comment] 2016-05-31 08:10
hy mickem!

thanks for your response!
the second one is the right, i added .txt for uplouding an dmp-file

kr
roland

**Comment by 00stormy00** [comment] 2016-06-09 11:54
hy again mickem!

sorry I'm late!
I was not able to upload the file before, now it schuld on the server

cheers roland

**Comment by mickem** [comment] 2016-06-22 18:03
I looked at the crash dump and it is a bit strange... are you using any plugins?
The crash seems to come from some CLR code i.e. not "nsclient++" but a module or possibly something similar?

**Comment by 00stormy00** [comment] 2016-06-23 18:31
hy mickem!

thanks for your response!
no i'm not using andy plugins. the first time i installed the nsclient++ with the icinga2 client.
so there i got first the problem i tried to update to the latest version of ns++
bevor reinstallation i deleted the folder c:\program files\nsclient++

hope you have a solution

many thanks

roland

**Comment by mickem** [comment] 2016-06-26 04:29
Question, are you using nsclient++ "from the icinga client" ? I know from before Icinga do some very strange things with NSClient++.

Could you try running NSClient++ stand alone?

**Comment by 00stormy00** [comment] 2016-06-27 06:47
Hy Mickem!

Yes, I using NSClient with Icinga 2 V2.4.8

Now I did the following:
I desabled the icinga2 Client
Uninstalled nsclient++
deleted C:\Program files\nsclient++
searchd for relevant nsclient++ registry keys (nothing interesting found)
installed nsclient++ V 0.5.0.45-x64
tested nsclient once again as following:
(If you need the dumps I can send this)

`
Hy Mickem!

Yes, I using NSClient with Icinga 2 V2.4.8

Now I did the following:
I desabled the icinga2 Client
Uninstalled nsclient++
deleted C:\Program files\nsclient++
searchd for relevant nsclient++ registry keys (nothing interesting found)
installed nsclient++ V 0.5.0.45-x64
tested nsclient once again as following:

c:\Program Files\NSClient++>"C:\Program Files\NSClient++\nscp.exe" client --load -all --log critical service=GDScan service=AVKProxy service=AVKWCtl "service=AntiVirusKit Client" -b -q check_service
INF: Detected crash...
INF: Running: "C:\Program Files\NSClient++\reporter.exe" "archive" "C:\Users\sbsadmin\AppData\Local\Temp\\397a1fc6-c91d-4167-90c0-a3a11802a684.dmp" "NSClient++" "0.5.0.45" "2016-04-15" "C:\Program Files\NSClient++/crash-dumps"
INF: Running: "C:\Program Files\NSClient++\reporter.exe" "restart" "NSCP"

c:\Program Files\NSClient++>Stopping service.
Starting NSCP



c:\Program Files\NSClient++>"C:\Program Files\NSClient++\nscp.exe" client --load -all --log critical -b -q check_os_version
INF: Detected crash...
INF: Running: "C:\Program Files\NSClient++\reporter.exe" "archive" "C:\Users\sbsadmin\AppData\Local\Temp\\56768d6b-16f6-4be2-84b9-2546df709d2a.dmp" "NSClient++" "0.5.0.45" "2016-04-15" "C:\Program Files\NSClient++/crash-dumps"
INF: Running: "C:\Program Files\NSClient++\reporter.exe" "restart" "NSCP"

c:\Program Files\NSClient++>Stopping service.
Starting NSCP
`

**Comment by rajo** [comment] 2016-09-07 13:15
Okay - same problem here: Windows Server2008 R2, installed latest icinga2 client and nsclient++ (just the plugins) and I am witnessing "INF: Detected crash..." 
I can as well confirm that just using the command like as follows will crash:
`
C:\Program Files\NSClient++>nscp.exe client --load -all --log critical service=icinga2 -b -q check_service
INF: Detected crash...
INF: Running: "C:\Program Files\NSClient++\reporter.exe" "archive" "C:\Users\ADMINI~1\AppData\Local\Temp\2\\e4d22042-116e-454e-8707-7150c66b176d.dmp" "NSClient++" "0.4.4.19" "2015-12-08" "C:\Program Files\NSClient++/crash-dumps"
Created folder: C:\Program Files\NSClient++/crash-dumps
INF: Running: "C:\Program Files\NSClient++\reporter.exe" "restart" "NSCP"
C:\Program Files\NSClient++>Stopping service.
Starting NSCP
C:\Program Files\NSClient++>
`
Any hints/ideas?
[e4d22042-116e-454e-8707-7150c66b176d.dmp.txt](https://github.com/mickem/nscp/files/459165/e4d22042-116e-454e-8707-7150c66b176d.dmp.txt)

[e4d22042-116e-454e-8707-7150c66b176d.zip](https://github.com/mickem/nscp/files/459168/e4d22042-116e-454e-8707-7150c66b176d.zip)

**Comment by rajo** [comment] 2016-09-07 13:45
okay, found possible solution:  @00stormy00 check that the proper .NET-Version is installed! this made it work for me

**Comment by 00stormy00** [comment] 2016-09-12 20:17
hy rajo

many thanks, i will check the version

kr

2016-09-07 15:45 GMT+02:00 rajo <notifications@github.com>:

**Comment by watermelonwatermelon** [comment] 2016-11-04 21:37
I'm having the same exact problem as you two. Any update?

I have .NET Framework 4.6.1.

**Comment by mickem** [comment] 2016-12-02 17:15
I havent had time to debug this as I had to get some stuff for OSMC ready...
But for sure seems to be related to the dot net thingy.
I will investigate a bit in the next few weeks, possibly remove the dotnet from the load in the web ui?

**Comment by mickem** [comment] 2017-07-28 17:11
This issue seems to have disapered (closed in other tickets) if anyone can reproduce it with latest builds please do let me know...

**Closed by mickem** 2017-07-28 17:11 UTC
